-- Demonic tasks batch 5
INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100997, 'Fill something up from a water pump', 'Fill something up from a water pump.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101062, 'Give Oli some Stew', 'Give Oli some Stew in Civitas illa Fortis.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101084, 'Inspect a green flame', 'Inspect a Green flame, near Salvagers outlook.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101105, 'Defeat a Buffalo', 'Defeat a Buffalo.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101110, 'Defeat a Guard in Varlamore underground', 'Defeat a Guard in Varlamore underground.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101124, 'Defeat a Seagull', 'Defeat a Seagull.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101129, 'Defeat a thief', 'Defeat a thief.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101132, 'Defeat an Icefiend in Varlamore', 'Defeat an Icefiend in Varlamore.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101133, 'Defeat an Imp in a basement', 'Defeat an Imp in the Kastori basement in Varlamore.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101175, 'Milk a Buffalo', 'Milk a Buffalo.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101193, 'Mine some coal from Stone cutter outpost', 'Mine some coal from Stone cutter outpost.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101326, 'Pet a Caique', 'Pet a Caique near the statue of Ates in Kastori or in the north of the Tlati Rainforest.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101328, 'Pet Renu', 'Pet Renu.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101329, 'Pet Xolo in Civitas', 'Pet Xolo in Civitas illa Fortis.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101339, 'Pick some Sweetcorn from a Field', 'Pick some Sweetcorn from a Field.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101454, 'Salute next to a statue of Quoatlos', 'Salute next to a statue of Quoatlos.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101455, 'Scatter some Ashes in Yama''s lair', 'Scatter some Ashes in Yama''s lair.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101462, 'Shear an Alpaca', 'Shear an Alpaca.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101464, 'Sit near a stolen cabbage', 'Sit near a stolen cabbage.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101508, 'Step onto an Ent trail', 'Step onto an Ent trail.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101522, 'Talk to a Gladiator', 'Talk to a Gladiator.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101550, 'Travel in Achilka''s boat', 'Travel in Achilka''s boat at one of her destinations along the River Varla.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101551, 'Travel to Aldarin via Fairy ring', 'Travel to Aldarin via Fairy ring.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101553, 'Travel using the Quetzal Transport System', 'Travel using the Quetzal Transport System.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101554, 'Trim your beard in Cam torum', 'Trim your beard in Cam torum.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (101603, 'Witness the gemstone Crab burrow away', 'Witness the gemstone crab burrow away.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100003, 'Defeat Amoxliatl 1 Time', 'Defeat the Amoxliatl in Varlamore.', 'Medium', 40, 'Varlamore', 'The Heart of Darkness', 'demonic', false),
  (100009, 'Defeat Hueycoatl 1 Time', 'Defeat the Hueycoatl in Varlamore.', 'Medium', 40, 'Varlamore', NULL, 'demonic', true),
  (100086, 'Activate all Statues of Ates', 'Activate all statues of ates.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100092, 'Activate the Statue of Ates', 'Activate the Statue of Ates in Aldarin.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100113, 'Break down 10 calcified deposits', 'Break down 10 Calcified deposits.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100118, 'Build a Quetzal Landing Site', 'Build a Quetzal Landing Site.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100137, 'Bury some wyrm bones near a Wyrm skeleton', 'Bury some wyrm bones or wyrmling bones near a Wyrm skeleton.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100187, 'Catch a Jerboa', 'Catch an Embertailed jerboa.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100192, 'Catch a Pyre fox', 'Catch a Pyre fox.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100257, 'Complete 10 Hunter Rumours', 'Complete 10 Hunter Rumours.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100258, 'Complete 10 laps of the Varlamore Agility Course', 'Complete 10 laps of the Colossal Wyrm Agility Course', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100263, 'Complete 25 Hunter Rumours', 'Complete 25 Hunter Rumours.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100276, 'Complete a Hunter Rumour', 'Complete a Hunter Rumour.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100279, 'Complete a Ribbiting Tale', 'Complete a Ribbiting Tale of a Lily Pad Labour Dispute.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100285, 'Complete At First Light', 'Complete the At First Light quest.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100287, 'Complete Death on the Isle', 'Complete Death on the Isle.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100292, 'Complete Meat and Greet', 'Complete Meat and Greet.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100298, 'Complete Shadows of Custodia', 'Complete the Shadows of Custodia quest.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100346, 'Complete the Heart of Darkness', 'Complete The Heart of Darkness quest.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100394, 'Complete Wave 1 of Fortis Colosseum', 'Complete Wave 1 of Fortis Colosseum.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100459, 'Create a Quetzal Whistle', 'Create a Quetzal Whistle.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100670, 'Enter a dark cave in Varlamore', 'Enter a dark cave in varlamore, near the Hunter Guild.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100795, 'Equip a piece of Alchemists outfit', 'Equip a piece of Alchemists outfit from the Mixology shop.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100799, 'Equip a piece of Hueycoatl armour', 'Equip a piece of Hueycoatl armour.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100866, 'Equip an egg', 'Hold an egg in your hands.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100885, 'Equip an orange', 'Equip an orange.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100890, 'Equip any piece of armour from the moons of peril', 'Equip any piece of armour from the Blood, Frost, or Eclipse moon set.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100899, 'Equip Earthbound Tecpatl', 'Equip the Earthbound tecpatl.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100922, 'Equip Glacial Temotli', 'Equip the Glacial temotli.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100926, 'Equip Pendant of Ates', 'Equip the Pendant of ates.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100937, 'Equip Sulphur Blades', 'Equip the Sulphur blades.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100969, 'Exchange an Ent seed with an Ent', 'Exchange an Ent seed with an Ent.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (100993, 'Fill a Grape Barrel for the Foreman', 'Fill a Grape Barrel for the Foreman in Aldarin.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101001, 'Fish a House Key', 'Fish a House Key.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101027, 'Fully decorate a Maple totem in the Auburn Valley', 'Fully decorate an Maple totem in the Auburn Valley.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101029, 'Fully decorate a Willow totem in the Auburn Valley', 'Fully decorate a Willow totem in the Auburn Valley.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101031, 'Fully decorate an Oak totem in the Auburn Valley', 'Fully decorate an Oak totem in the Auburn Valley.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101085, 'Jump on Yama''s stepping stones 666 times', 'Jump on Yama''s stepping stones in his League domain 666 times.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101088, 'Defeat 10 Frost Crabs', 'Defeat 10 Frost Crabs.', 'Medium', 40, 'Varlamore', 'The Heart of Darkness', 'demonic', false),
  (101106, 'Defeat a Dire Wolf', 'Defeat a Dire Wolf in Varlamore.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101109, 'Defeat a fully grown jaguar without taking any damage from it', 'Defeat a fully grown jaguar without taking any damage from it.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101117, 'Defeat a Oryx with melee', 'Defeat an Oryx in the Avium Savannah with melee.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101168, 'Make a Greenman statue', 'Make a Greenman statue.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101180, 'Mine 20 Mithril Ore in the Stonecutter Outpost', 'Mine 20 Mithril Ore in the Stonecutter Outpost.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101183, 'Mine 250 Blessed Bone Shards', 'Mine 250 Blessed Bone Shards.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101322, 'Pay an Urchin for Information', 'Pay an Urchin for Information in the Stealing Valuables minigame.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101349, 'Pickpocket a knight of varlamore 20 times', 'Pickpocket a Knight of Varlamore 20 times.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101491, 'Steal 100 Valuables', 'Steal 100 Valuables.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101493, 'Steal 15 House Keys', 'Steal 15 House Keys.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101494, 'Steal 25 Valuables', 'Steal 25 Valuables.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101500, 'Steal a House Key', 'Steal a House Key.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101506, 'Steal from the Fortis Spice Stall', 'Steal from the Fortis Spice Stall.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101510, 'Store some bowstrings inside a bowstring spool', 'Store some bowstrings inside a bowstring spool.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101511, 'Defeat the Moons of Peril', 'Defeat the Moons of Peril.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101512, 'Defeat the Moons of Peril 10 times', 'Defeat the Moons of Peril 10 times.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101513, 'Defeat the Moons of Peril 25 times', 'Defeat the Moons of Peril 25 times.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101528, 'Teleport to Cam Torum using a Calcified Moth', 'Teleport to Cam Torum using a Calcified Moth.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101529, 'Teleport to Civitas illa Fortis', 'Teleport to Civitas illa Fortis using the standard spellbook.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false),
  (101589, 'Use the pottery oven in Civitas', 'Use the pottery oven in Civitas to make something out of clay.', 'Medium', 40, 'Varlamore', NULL, 'demonic', false);
