-- Demonic tasks batch 3
INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (101476, 'Smith 10 Steel bolts (unf)', 'Use an Anvil to smith 10 Steel bolts (unf).', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101477, 'Smith 150 Iron Arrowtips', 'Use an Anvil to smith 150 Iron Arrowtips.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101478, 'Smith 250 Mithril bolts (unf)', 'Use an Anvil to smith 250 Mithril bolts (unf)', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101481, 'Smith a Steel 2h sword', 'Use an Anvil to smith a Steel 2h sword.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101488, 'Snare a Bird 20 times', 'Snare a Bird 20 times.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101515, 'Successfully Cook 5 Pieces of Food', 'Cook 5 pieces of food in a row without burning them.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101518, 'Successfully pickpocket a Citizen 10 times in a row', 'Successfully pickpocket a Citizen 10 times in a row without failing.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101531, 'Teleport Using Law Runes', 'Cast any teleport spell that uses Law Runes.', 'Medium', 40, 'General', 'or with , or Grimoire', 'demonic', false),
  (101544, 'Trade a herb with Jekyll', 'Trade a herb with Jekyll for a potion.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101570, 'Upset the Sandwich lady', 'Make the Sandwich lady quite cross with you.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100167, 'Catch 200 Implings in Puro-Puro', 'Catch 200 Implings in Puro-Puro.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100280, 'Complete all tasks for 1 boss', 'Complete all of the Combat Achievements available at 1 boss within the areas you have unlocked.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100282, 'Complete all tasks for 3 bosses', 'Complete all of the Combat Achievements available at 3 different bosses within the areas you have unlocked.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100402, 'Cook 100 pies', 'Cook 100 pies.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100407, 'Cook 25 Meat Pies', 'Cook 25 Meat pies.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100460, 'Create a Red D''hide Shield', 'Create a Red d''hide shield.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101279, 'Obtain a High level tree seed from a birds nest', 'Obtain either a Magic, Dragonfruit, Redwood or Spirit seed from a birds nest.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100110, 'Blow 100 Light Orbs', 'Blow 100 Empty light orbs.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100116, 'Build a Gilded Altar', 'Build a Gilded Altar in a Chapel in your Player Owned House.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100994, 'Fill a Hard STASH Unit', 'Build a Hard Stash unit and fill it with the relevant items.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100124, 'Burn 100 Yew Logs', 'Burn 100 Yew Logs.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100131, 'Burn Some Magic Logs', 'Burn some Magic Logs.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100142, 'Cast a Wave Spell', 'Cast any wave spell.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100161, 'Catch 100 Shark', 'Catch 100 Raw Shark whilst Fishing.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100185, 'Catch a Dragon Impling', 'Catch a Dragon Impling.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100222, 'Chop 100 Yew Logs', 'Chop 100 Yew Logs.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100227, 'Chop 75 Magic Logs', 'Chop 75 Magic Logs from Magic Trees.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100237, 'Clean 100 Grimy Avantoe', 'Clean 100 Grimy Avantoe.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100241, 'Clean 50 Grimy Lantadyme', 'Clean 50 Grimy Lantadyme.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100266, 'Complete 5 Speed Tasks', 'Complete 5 Combat Achievement Speed tasks.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100255, 'Complete 1 Speed Task', 'Complete a Combat Achievement Speed task.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100403, 'Cook 100 Sharks', 'Cook 100 Raw Sharks.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100415, 'Craft 100 Unpowered Orbs', 'Craft 100 Unpowered Orbs.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100420, 'Craft 30 Blue Dragonhide Bodies', 'Craft 30 Blue Dragonhide Bodies.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100427, 'Craft a Dragonstone Amulet', 'Craft a Dragonstone Amulet.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100458, 'Create a Mithril Grapple', 'Create a Mithril Grapple.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101087, 'Defeat 1 unique Echo Boss', 'Defeat 1 unique Echo Boss.', 'Hard', 80, 'General', NULL, 'demonic', true),
  (100024, 'Defeat 100 Superior slayer creatures', 'Defeat 100 Superior slayer creatures.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101090, 'Defeat 2 unique Echo Bosses', 'Defeat 2 unique Echo Bosses.', 'Hard', 80, 'General', NULL, 'demonic', true),
  (101091, 'Defeat 25 Echo Bosses', 'Defeat 25 Echo Bosses.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101092, 'Defeat 3 unique Echo Bosses', 'Defeat 3 unique Echo Bosses.', 'Hard', 80, 'General', NULL, 'demonic', true),
  (100585, 'Defeat the Abyssal Sire', 'Defeat the Abyssal Sire in the Abyssal Nexus.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100966, 'Equip 2 unique Echo Items', 'Equip 2 unique Echo Items.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100963, 'Equip 3 unique Echo Items', 'Equip 3 unique Echo Items.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100730, 'Equip a Full Black Dragonhide Set', 'Equip a Black Dragonhide Body, some Black Dragonhide Chaps and some Black Dragonhide Vambraces.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100735, 'Equip a Full God Dragonhide Set', 'Equip a Blessed Coif, Body and Chaps with all pieces aligned to the same god.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100845, 'Equip a two-handed Axe', 'Equip a Felling axe.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100777, 'Equip a Magic Shortbow', 'Equip a Magic Shortbow.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100782, 'Equip a Mist Battlestaff', 'Equip a Mist battlestaff.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100820, 'Equip a Rune Crossbow', 'Equip a Rune Crossbow.', 'Hard', 80, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100747, 'Equip a Full Rune Set', 'Equip a Rune Platebody, a Rune Full Helm and either some Rune Platelegs or a Rune Plateskirt.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100736, 'Equip a Full God Rune Set', 'Equip a full set of God Rune Armour with all pieces aligned to the same god.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100760, 'Equip a Full Vestment Set', 'Equip a full set of Vestment robes with all pieces aligned to the same god.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100933, 'Equip some Ranger Boots', 'Equip a pair of Ranger Boots.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100718, 'Equip a Dragon Weapon', 'Equip any Dragon weapon.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100886, 'Equip an Ornament Kit Item', 'Equip any item that has an Ornament Kit attached to it.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100696, 'Equip a Combination Battlestaff or Mystic Staff', 'Equip either a Combination Battlestaff or a Combination Mystic Staff.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100763, 'Equip a Gilded or Trimmed Wizard Item', 'Equip either a Gilded armour item or trimmed wizard item.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101371, 'Reach a Prayer Bonus of 30', 'Equip enough items to reach a Prayer Bonus of 30 or more.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100923, 'Equip one unique Echo Item', 'Equip one unique echo item.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100975, 'Fill 10 Elite Clue Collection Log Slots', 'Fill 10 slots in the Elite Clue section of the Collection Log.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100979, 'Fill 25 Elite Clue Collection Log Slots', 'Fill 25 slots in the Elite Clue section of the Collection Log.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100983, 'Fill 30 Hard Clue Collection Log Slots', 'Fill 30 slots in the Hard Clue section of the Collection Log.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100984, 'Fill 40 Medium Clue Collection Log Slots', 'Fill 40 slots in the Medium Clue section of the Collection Log.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100986, 'Fill 5 Master Clue Collection Log Slots', 'Fill 5 slots in the Master Clue section of the Collection Log.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100988, 'Fill 50 Easy Clue Collection Log Slots', 'Fill 50 slots in the Easy Clue section of the Collection Log.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100992, 'Fill a Giant Pouch', 'Fill a Giant Pouch with Essence.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101007, 'Fletch 200 Magic Longbow (u)', 'Fletch 200 Magic Longbow (u).', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101012, 'Fletch 50 Yew longbow (u)', 'Fletch 50 Yew longbow (u).', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101013, 'Fletch a Magic Shield', 'Fletch a Magic Shield.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101014, 'Fletch a Rune Crossbow', 'Fletch a Rune Crossbow.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101033, 'Gain 10 Unique Items From Elite Clues', 'Gain 10 unique items from Elite Clue Scroll Reward Caskets.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101034, 'Gain 10 Unique Items From Master Clues', 'Gain 10 unique items from Master Clue Scroll Reward Caskets.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101039, 'Gain 25 Unique Items From Medium Clues', 'Gain 25 unique items from Medium Clue Scroll Reward Caskets.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101042, 'Gain 50 Unique Items From Hard Clues', 'Gain 50 unique items from Hard Clue Scroll Reward Caskets.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101047, 'Gain a Unique Item From an Elite Clue', 'Gain a unique item from an Elite Clue Scroll Reward Casket.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101157, 'Make 20 Ranging Potions', 'Make 20 Ranging Potions.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101170, 'Make a Saradomin Brew', 'Make a Saradomin Brew.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101186, 'Mine 50 Adamantite Ore', 'Mine 50 Adamantite Ore.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101190, 'Mine a shooting star', 'Mine a shooting star.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100020, '100 Collection log slots', 'Obtain 100 unique Collection Log slots.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100032, '200 Collection log slots', 'Obtain 200 unique Collection Log slots.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101296, 'Offer an Unsired to the Font of Consumption', 'Offer an Unsired to the Font of Consumption in the Abyssal Nexus.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100038, '25 Master Clue Scrolls', 'Open 25 Reward caskets for completing Master clue scrolls.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100065, '75 Elite Clue Scrolls', 'Open 75 Reward caskets for completing Elite clue scrolls.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100066, '75 Hard Clue Scrolls', 'Open 75 Reward caskets for completing Hard clue scrolls.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100010, '1 Master Clue Scroll', 'Open a Reward casket for completing a Master clue scroll.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101415, 'Reach Total Level 1000', 'Reach a Total Level of 1000.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101416, 'Reach Total Level 1250', 'Reach a Total Level of 1250.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101417, 'Reach Total Level 1500', 'Reach a Total Level of 1500.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101418, 'Reach Total Level 1750', 'Reach a Total Level of 1750.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101383, 'Reach Combat Level 100', 'Reach Combat Level 100.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101384, 'Reach Combat Level 110', 'Reach Combat Level 110.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101375, 'Reach Base Level 40', 'Reach level 40 in every skill.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101377, 'Reach Base Level 50', 'Reach level 50 in every skill.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101378, 'Reach Base Level 60', 'Reach level 60 in every skill.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100080, 'Achieve Your First Level 70', 'Reach level 70 in any skill.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101379, 'Reach Base Level 70', 'Reach level 70 in every skill.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100081, 'Achieve Your First Level 80', 'Reach level 80 in any skill.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101437, 'Restore 75 Prayer Points at an Altar', 'Restore 75 or more Prayer Points at any altar.', 'Hard', 80, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (101480, 'Smith a Rune Item', 'Smith a Runite Item.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101503, 'Steal From a Gem Stall', 'Steal from a Gem Stall.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100105, 'Beat Jacky Jester', 'Successfully copy Jacky the Jester to win.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100974, 'Ferment 100 Jugs of Wine', 'Successfully ferment 100 Jugs of Wine.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100419, 'Craft 2500 Essence Into Runes', 'Use Runecrafting Altars to craft 2500 essence into runes of any type.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (101470, 'Smelt a Runite Bar', 'Use a Furnace to smelt a Runite Bar.', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100247, 'Combat Achievements Easy Tier', '', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100479, 'Defeat 10 Superior slayer creatures', '', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100481, 'Defeat 20 Superior slayer creatures', '', 'Hard', 80, 'General', NULL, 'demonic', false),
  (100261, 'Complete 200 Slayer Tasks', 'Complete 200 Slayer Tasks.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100281, 'Complete all tasks for 10 bosses', 'Complete all of the Combat Achievements available at 10 different bosses within the areas you have unlocked.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100283, 'Complete all tasks for 5 bosses', 'Complete all of the Combat Achievements available at 5 different bosses within the areas you have unlocked.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101191, 'Mine a size 8+ shooting star', 'Mine a shooting star which is either size 8 or 9.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101201, 'Obtain 100 Million XP in a combat skill', 'Obtain 100 million experience in either Attack, Strength, Defence, Magic, Ranged, Hitpoints or Prayer.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101202, 'Obtain 100 Million XP in any non-combat skill', 'Obtain 100 million experience in any non-combat skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101223, 'Obtain 25 Million XP in 5 non-combat skills', 'Obtain 25 million experience in 5 different skills excluding Attack, Strength, Defence, Magic, Ranged & Hitpoints.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101224, 'Obtain 25 Million XP in a combat skill', 'Obtain 25 million experience in either Attack, Strength, Defence, Magic, Ranged or Hitpoints.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101242, 'Obtain 35 Million XP in 3 non-combat skills', 'Obtain 35 million experience in 3 different skills excluding Attack, Strength, Defence, Magic, Ranged and Hitpoints.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101243, 'Obtain 35 Million XP in a combat skill', 'Obtain 35 million experience in either Attack, Strength, Defence, Magic, Ranged or Hitpoints.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100093, 'Add a Jar to a Display Case', 'Add a Jar to a Display Case in your Player Owned House Achievement Gallery.', 'Elite', 200, 'General', 'Check associated bosses', 'demonic', false),
  (100175, 'Catch 500 Chinchompas', 'Catch 500 Chinchompas.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100259, 'Complete 10 Speed Tasks', 'Complete 10 Combat Achievement Speed tasks.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100021, '100 Combat Achievements', 'Complete 100 Combat Achievements', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100028, '150 Combat Achievements', 'Complete 150 Combat Achievements', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100260, 'Complete 20 Speed Tasks', 'Complete 20 Combat Achievement Speed tasks.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100033, '200 Combat Achievements', 'Complete 200 Combat Achievements', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100043, '250 Combat Achievements', 'Complete 250 Combat Achievements', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100265, 'Complete 30 Speed Tasks', 'Complete 30 Combat Achievement Speed tasks.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100057, '50 Combat Achievements', 'Complete 50 Combat Achievements', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100071, 'Abyssal Sire Combat Achievements', 'Complete all of the Combat Achievements for Abyssal Sire.', 'Elite', 200, 'General', 'See Abyssal Sire#Combat Achievements', 'demonic', false),
  (100441, 'Craft an Onyx Amulet', 'Craft an Onyx Amulet.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100874, 'Equip an Eternal Slayer Ring', 'Craft and equip an Eternal slayer ring.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101089, 'Defeat 150 Echo Bosses', 'Defeat 150 Echo Bosses.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101094, 'Defeat 4 unique Echo Bosses', 'Defeat 4 unique Echo Bosses.', 'Elite', 200, 'General', NULL, 'demonic', true),
  (100483, 'Defeat 50 Superior slayer creatures', 'Defeat 50 Superior Slayer Creatures.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101099, 'Defeat 75 Echo Bosses', 'Defeat 75 Echo Bosses.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100586, 'Defeat the Abyssal Sire 150 Times', 'Defeat the Abyssal Sire in the Abyssal Nexus 150 times.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100587, 'Defeat the Abyssal Sire 300 Times', 'Defeat the Abyssal Sire in the Abyssal Nexus 300 times.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100588, 'Defeat the Abyssal Sire 50 Times', 'Defeat the Abyssal Sire in the Abyssal Nexus 50 times.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100720, 'Equip a Dragonfire Shield', 'Equip a Dragonfire Shield.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100856, 'Equip an Abyssal Bludgeon', 'Equip an Abyssal Bludgeon.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100857, 'Equip an Abyssal Dagger', 'Equip an Abyssal Dagger.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100859, 'Equip an Abyssal Whip', 'Equip an Abyssal Whip.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100812, 'Equip a piece of Virtus', 'Equip either the Virtus Mask, Robe top, or Robe Bottoms.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100905, 'Equip four unique Echo Items', 'Equip four unique echo items.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100954, 'Equip the Soulreaper Axe', 'Equip the Soulreaper Axe.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100980, 'Fill 25 Master Clue Collection Log Slots', 'Fill 25 slots in the Master Clue section of the Collection Log.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101002, 'Fletch 100 Dragon Javelins', 'Fletch 100 Dragon Javelins.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101037, 'Gain 25 Unique Items From Elite Clues', 'Gain 25 unique items from Elite Clue Scroll Reward Caskets.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101038, 'Gain 25 Unique Items From Master Clues', 'Gain 25 unique items from Master Clue Scroll Reward Caskets.', 'Elite', 200, 'General', NULL, 'demonic', false);
