-- Demonic tasks batch 2
INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100056, '50 Collection log slots', 'Obtain 50 unique Collection Log slots.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100064, '75 Easy Clue Scrolls', 'Open 75 Reward caskets for completing Easy clue scrolls.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100068, '75 Medium Clue Scrolls', 'Open 75 Reward caskets for completing Medium clue scrolls.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100069, 'Defeat 75 Superior slayer creatures', '', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100074, 'Achieve Your First Level 20', 'Reach level 20 in any skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100075, 'Achieve Your First Level 30', 'Reach level 30 in any skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100076, 'Achieve Your First Level 40', 'Reach level 40 in any skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100078, 'Achieve Your First Level 50', 'Reach level 50 in any skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100079, 'Achieve Your First Level 60', 'Reach level 60 in any skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100091, 'Activate Smite', 'Activate Smite in your prayer book', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100117, 'Build a Mahogany Portal', 'Build a Mahogany Portal in a Portal Chamber in your Player Owned House.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100119, 'Build a Room in Your Player Owned House', 'Build a room in your Player Owned House.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100122, 'Build an Oak Larder', 'Build an Oak Larder in a Kitchen in your Player Owned House.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100123, 'Burn 100 Willow Logs', 'Burn 100 Willow Logs.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100128, 'Burn 25 Maple Logs', 'Burn 25 Maple Logs.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100129, 'Burn Some Coloured Logs', 'Burn some logs that have been coloured with a firelighter.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100138, 'Bury Some Wyvern or Dragon Bones', 'Bury either some Wyvern Bones or some Dragon Bones.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100139, 'Butter a potato', 'Make a potato with butter', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100143, 'Cast an Earth Blast Spell', 'Cast an Earth Blast Spell', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100154, 'Cast Low Level Alchemy', 'Cast the Low Level Alchemy spell', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100159, 'Catch 10 Cod', 'Catch 10 Cod', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100162, 'Catch 100 Swordfish', 'Catch 100 Swordfish', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100163, 'Catch 100 Tuna', 'Catch 100 Tuna', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100166, 'Catch 20 mackerel', 'Catch 20 Raw mackerel whilst Fishing', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100171, 'Catch 50 Implings in Puro-Puro', 'Catch 50 Implings in Puro-Puro.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100174, 'Catch 50 Tuna', 'Catch 50 Tuna', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100176, 'Catch 75 Lobsters', 'Catch 75 Lobsters', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100177, 'Catch 75 Trout', 'Catch 75 Raw Trout whilst Fishing', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100181, 'Catch a Butterfly', 'Catch any butterfly', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100200, 'Catch a Swamp Lizard or Salamander', 'Catch either a Swamp Lizard or any kind of Salamander.', 'Medium', 40, 'General', 'Either (), (), (, (), ()', 'demonic', false),
  (100211, 'Check a grown Fruit Tree', 'Check the health of any Fruit Tree you''ve grown.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100215, 'Check a grown Tree', 'Check the health of any regular Tree you''ve grown', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100221, 'Chop 100 Willow Logs', 'Chop 100 Willow Logs from Willow Trees.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100233, 'Chop Some Logs With a Rune Axe', 'Chop any kind of logs using a Rune Axe.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100235, 'Chop some Rising Roots', 'Chop some Rising Roots spawned via Forestry.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100236, 'Churn some butter', 'Use a churn to make some butter.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100240, 'Clean 50 Grimy Cadantine', 'Clean 50 Grimy Cadantine.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100242, 'Clean 50 Grimy Ranarr Weed', 'Clean 50 Grimy Ranarr Weed.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100243, 'Clean a Grimy Avantoe', 'Clean a Grimy Avantoe.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100254, 'Complete 1 Slayer Task', 'Complete 1 Slayer Task.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100327, 'Complete the Evil Bob random event', 'Complete the Evil Bob random event.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100332, 'Complete the Flowering Bush event', 'Complete the Flowering Bush event spawned via Forestry.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100351, 'Complete the Maze random event', 'Complete the Maze random event.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100363, 'Complete the Pheasant Forestry Event', 'Complete the Pheasant event spawned via Forestry.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100364, 'Complete the Pillory random event', 'Complete the Pillory random event', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100365, 'Complete the Pinball random event', 'Complete the Pinball random event', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100366, 'Complete the Postie Pete random event', 'Complete the Postie Pete random event.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100369, 'Complete the Prison Pete random event', 'Complete the Prison Pete random event.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100371, 'Complete the Ritual Forestry Event', 'Complete the Ritual event spawned via Forestry.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100375, 'Complete the Struggling Sapling event', 'Complete the Struggling Sapling event spawned via Forestry.', 'Medium', 40, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100376, 'Complete the Surprise Exam random event', 'Complete the Surprise Exam random event.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100398, 'Convert an item into at least 500 coins', 'Cast the High Level Alchemy spell to convert an item into 500 coins or more', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100404, 'Cook 100 Swordfish', 'Cook 100 Swordfish', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100408, 'Cook 50 Tuna', 'Cook 50 Raw Tuna', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100417, 'Craft 20 Silver items', 'Craft 20 Silver items using Silver bars', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100418, 'Craft 200 Essence Into Runes', 'Use Runecrafting Altars to craft 200 essence into runes of any type.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100433, 'Craft a Sapphire Amulet', 'Craft a Sapphire amulet.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100439, 'Craft an Emerald Ring', 'Craft an Emerald Ring.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100442, 'Craft Any Combination Rune', 'Use a Runecrafting Altar to craft any type of combination rune.', 'Medium', 40, 'General', 'Either (), (), , (', 'demonic', false),
  (100472, 'Chop 50 Maple Logs', 'Chop 50 Maple Logs.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100527, 'Defeat a Superior slayer creature', 'Defeat a Superior slayer creature.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100665, 'Eat a piece of food that restores at least 6 hitpoints', 'Eat a piece of food that restores at least 6 hitpoints', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100668, 'Eat some Purple Sweets', 'Eat some Purple Sweets.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100726, 'Equip a Full Adamant Set', 'Equip an Adamant Platebody, a Adamant Full Helm and either some Adamant Platelegs or an Adamant Plateskirt.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100731, 'Equip a Full Blue Dragonhide Set', 'Equip a Blue Dragonhide Body, some Blue Dragonhide Chaps and some Blue Dragonhide Vambraces.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100732, 'Equip a Full Bronze Set', 'Equip a Bronze Platebody, a Bronze Full Helm and either some Bronze Platelegs or a Bronze Plateskirt', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100744, 'Equip a Full Red Dragonhide Set', 'Equip a Red Dragonhide Body, some Red Dragonhide Chaps and some Red Dragonhide Vambraces.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100783, 'Equip a Mithril Weapon', 'Equip any Mithril weapon.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100794, 'Equip a Piece of a Mystic Set', 'Equip any piece of any Mystic robe set.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100797, 'Equip a piece of Beekeeper''s Outfit', 'Equip a piece of Beekeeper''s Outfit.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100798, 'Equip a piece of Camouflage outfit', 'Equip a piece of Camouflage outfit.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100801, 'Equip a piece of Mime Outfit', 'Equip a piece of Mime Outfit.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100814, 'Equip a piece of Zombie Outfit', 'Equip a piece of Zombie Outfit.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100821, 'Equip a Rune Weapon', 'Equip any Rune weapon.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100841, 'Equip a Trimmed Amulet', 'Equip a Trimmed Amulet.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100850, 'Equip a Willow Shield', 'Equip a Willow Shield.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100851, 'Equip a Yew Shortbow', 'Equip a Yew Shortbow.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100860, 'Equip an Adamant Weapon', 'Equip any Adamant weapon.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100868, 'Equip an Elemental Battlestaff or Mystic Staff', 'Equip either an elemental battlestaff or an elemental mystic staff.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100927, 'Equip some Black armour', 'Equip either a Black Platebody, some Black Platelegs or a Black Full Helm.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100934, 'Equip some Steel armour', 'Equip either a Steel Platebody, some Steel Platelegs or a Steel Full Helm.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100949, 'Equip the Forestry Basket', 'Equip the Forestry Basket.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100976, 'Fill 15 Hard Clue Collection Log Slots', 'Fill 15 slots in the Hard Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100977, 'Fill 20 Easy Clue Collection Log Slots', 'Fill 20 slots in the Easy Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100978, 'Fill 20 Medium Clue Collection Log Slots', 'Fill 20 slots in the Medium Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100981, 'Fill 3 Elite Clue Collection Log Slots', 'Fill 3 slots in the Elite Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100982, 'Fill 3 Hard Clue Collection Log Slots', 'Fill 3 slots in the Hard Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100985, 'Fill 5 Easy Clue Collection Log Slots', 'Fill 5 slots in the Easy Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100987, 'Fill 5 Medium Clue Collection Log Slots', 'Fill 5 slots in the Medium Clue section of the Collection Log.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100990, 'Fill a Bucket With Supercompost', 'Fill a Bucket with Supercompost from a Compost Bin.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100995, 'Fill a Large Pouch', 'Fill a Large Pouch with Essence.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100996, 'Fill a Medium STASH Unit', 'Build a Medium STASH unit and fill it with the relevant items.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101004, 'Fletch 1000 arrow shafts', 'Fletch 1000 arrow shafts.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101005, 'Fletch 150 Iron Arrows', 'Fletch 150 Iron Arrows.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101008, 'Fletch 25 Maple longbow (u)', 'Fletch 25 Maple longbow (u).', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101009, 'Fletch 25 Oak Stocks', 'Fletch 25 Oak Stocks.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101011, 'Fletch 50 Willow longbow (u)', 'Fletch 50 Willow longbow (u).', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101015, 'Fletch a Willow Shortbow (u)', 'Fletch a Willow Shortbow (u).', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101019, 'Fletch some Broad Arrows or Bolts', 'Fletch either some Broad Arrows or some Broad Bolts.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101032, 'Gain 10 Unique Items From Easy Clues', 'Gain 10 unique items from Easy Clue Scroll Reward Caskets.', 'Medium', 40, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (101035, 'Gain 10 Unique Items From Medium Clues', 'Gain 10 unique items from Medium Clue Scroll Reward Caskets.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101036, 'Gain 20 Unique Items From Hard Clues', 'Gain 20 unique items from Hard Clue Scroll Reward Caskets.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101040, 'Gain 35 Unique Items From Easy Clues', 'Gain 35 unique items from Easy Clue Scroll Reward Caskets.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101041, 'Gain 5 Unique Items From Hard Clues', 'Gain 5 unique items from Hard Clue Scroll Reward Caskets.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101043, 'Gain a Unique Item From a Hard Clue', 'Gain a unique item from a Hard Clue Scroll Reward Casket.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101044, 'Gain a Unique Item From a Master Clue', 'Gain a unique item from a Master Clue Scroll Reward Casket.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101045, 'Gain a Unique Item From a Medium Clue', 'Gain a unique item from a Medium Clue Scroll Reward Casket.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101046, 'Gain a Unique Item From an Easy Clue', 'Gain a unique item from an Easy Clue Scroll Reward Casket.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101052, 'Get a Gem from a Gorak', 'Obtain a gem drop from a Gorak.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101061, 'Give an Entling a haircut', 'Give an entling a haircut via Forestry.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101072, 'Harvest a Ranarr Weed', 'Harvest an Ranarr Weed from any Herb patch.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101076, 'Have a Leprechaun send something to the bank', 'Have the Forestry leprechaun send something to your bank.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101095, 'Defeat 5 Bunnies', 'Defeat 5 Bunnies.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101096, 'Defeat 5 creatures with a mace', 'Defeat 5 creatures with a mace as the final hit.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101123, 'Defeat a Scorpion with a Mithril Spear', 'Defeat a Scorpion with a mithril spear as the final hit.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101137, 'Defeat 3 chickens in 6 seconds', 'Defeat 3 chickens in 6 seconds.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101143, 'Land a hoop on a stick', 'Successfully land a hoop on a stick in the PoH minigame.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101158, 'Make 20 Stamina Potions', 'Make 20 Stamina Potions.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101160, 'Make 30 Prayer Potions', 'Make 30 Prayer Potions.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101165, 'Make a 4 dose potion', 'Make any 4 dose potion using an Amulet of Chemistry.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101169, 'Make a Meat Pizza', 'Make a Meat Pizza', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101174, 'Make some Flour', 'Make some Flour in a windmill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101176, 'Mine 10 Silver', 'Mine 10 Silver ore', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101187, 'Mine 50 Iron Ore', 'Mine 50 Iron Ore.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101188, 'Mine 50 Mithril Ore', 'Mine 50 Mithril Ore.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101194, 'Mine some Ore With a Rune Pickaxe', 'Mine any ore using a Rune Pickaxe.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101271, 'Obtain 800 Coins From Coin Pouches At Once', 'Open a stack of Coin Pouches and obtain at least 800 Coins.', 'Medium', 40, 'General', '(can be completed at lower levels depending on luck when pickpocketing NPCs with variable coin amounts)', 'demonic', false),
  (101275, 'Obtain a Clue Geode While Mining', 'Obtain any kind of clue geode whilst Mining a rock.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101278, 'Obtain a Gem While Mining', 'Obtain any kind of gem whilst Mining a rock.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101280, 'Obtain a Kebab from a random event', 'Obtain a Kebab from any random event', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101284, 'Obtain an old boot from a fishing spot', 'Obtain an old boot from a fishing spot', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101305, 'Open 28 Coin Pouches At Once', 'Open 28 Coin Pouches at once.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101319, 'Open the Mystery Box', 'A boat is a boat, but the mystery box could be anything, even a boat!', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101350, 'Pickpocket a Master Farmer', 'Successfully pickpocket from a Master farmer.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101370, 'Reach a Prayer Bonus of 15', 'Equip enough item to reach a Prayer bonus of 15 or more.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101372, 'Reach Base Level 10', 'Reach level 10 in every skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101373, 'Reach Base Level 20', 'Reach level 20 in every skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101374, 'Reach Base Level 30', 'Reach level 30 in every skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101376, 'Reach Base Level 5', 'Reach level 5 in every skill.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101388, 'Reach Combat Level 50', 'Reach Combat Level 50.', 'Medium', 40, 'General', NULL, 'demonic', true),
  (101389, 'Reach Combat Level 75', 'Reach Combat Level 75.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101414, 'Reach Total Level 100', 'Reach a Total Level of 100.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101423, 'Reach Total Level 250', 'Reach a Total Level of 250.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101424, 'Reach Total Level 666', 'Reach Total Level 666.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101425, 'Reach Total Level 750', 'Reach a Total Level of 750.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101433, 'Redecorate your player Owned house', 'Redecorate your player Owned house.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101453, 'Sacrifice something to Deaths coffer', 'Sacrifice something to Deaths coffer.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101457, 'Scrape some Blue Dragonhide', 'Scrape some blue dragonhide.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101465, 'Slay 250 Creatures', 'Slay 250 creatures whilst on a Slayer Task.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (101471, 'Smelt a Steel Bar', 'Use a Furnace to smelt a Steel Bar.', 'Medium', 40, 'General', NULL, 'demonic', false);
