-- Demonic tasks batch 4
INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (101466, 'Slay an Abyssal Demon', 'Kill an Abyssal Demon whilst on an Abyssal Demon Slayer Task.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101171, 'Make a Super Combat Potion', 'Make a Super Combat Potion.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101206, 'Obtain 25 Million Agility XP', 'Obtain 25 million experience in your Agility skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101207, 'Obtain 25 Million Construction XP', 'Obtain 25 million experience in your Construction skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101208, 'Obtain 25 Million Cooking XP', 'Obtain 25 million experience in your Cooking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101209, 'Obtain 25 Million Crafting XP', 'Obtain 25 million experience in your Crafting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101210, 'Obtain 25 Million Farming XP', 'Obtain 25 million experience in your Farming skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101211, 'Obtain 25 Million Firemaking XP', 'Obtain 25 million experience in your Firemaking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101212, 'Obtain 25 Million Fishing XP', 'Obtain 25 million experience in your Fishing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101213, 'Obtain 25 Million Fletching XP', 'Obtain 25 million experience in your Fletching skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101214, 'Obtain 25 Million Herblore XP', 'Obtain 25 million experience in your Herblore skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101215, 'Obtain 25 Million Hunter XP', 'Obtain 25 million experience in your Hunter skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101216, 'Obtain 25 Million Mining XP', 'Obtain 25 million experience in your Mining skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101217, 'Obtain 25 Million Prayer XP', 'Obtain 25 million experience in your Prayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101218, 'Obtain 25 Million Runecraft XP', 'Obtain 25 million experience in your Runecraft skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101219, 'Obtain 25 Million Slayer XP', 'Obtain 25 million experience in your Slayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101220, 'Obtain 25 Million Smithing XP', 'Obtain 25 million experience in your Smithing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101221, 'Obtain 25 Million Thieving XP', 'Obtain 25 million experience in your Thieving skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101222, 'Obtain 25 Million Woodcutting XP', 'Obtain 25 million experience in your Woodcutting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101225, 'Obtain 35 Million Agility XP', 'Obtain 35 million experience in your Agility skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101226, 'Obtain 35 Million Construction XP', 'Obtain 35 million experience in your Construction skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101227, 'Obtain 35 Million Cooking XP', 'Obtain 35 million experience in your Cooking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101228, 'Obtain 35 Million Crafting XP', 'Obtain 35 million experience in your Crafting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101229, 'Obtain 35 Million Farming XP', 'Obtain 35 million experience in your Farming skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101230, 'Obtain 35 Million Firemaking XP', 'Obtain 35 million experience in your Firemaking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101231, 'Obtain 35 Million Fishing XP', 'Obtain 35 million experience in your Fishing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101232, 'Obtain 35 Million Fletching XP', 'Obtain 35 million experience in your Fletching skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101233, 'Obtain 35 Million Herblore XP', 'Obtain 35 million experience in your Herblore skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101234, 'Obtain 35 Million Hunter XP', 'Obtain 35 million experience in your Hunter skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101235, 'Obtain 35 Million Mining XP', 'Obtain 35 million experience in your Mining skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101236, 'Obtain 35 Million Prayer XP', 'Obtain 35 million experience in your Prayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101237, 'Obtain 35 Million Runecraft XP', 'Obtain 35 million experience in your Runecraft skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101238, 'Obtain 35 Million Slayer XP', 'Obtain 35 million experience in your Slayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101239, 'Obtain 35 Million Smithing XP', 'Obtain 35 million experience in your Smithing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101240, 'Obtain 35 Million Thieving XP', 'Obtain 35 million experience in your Thieving skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101241, 'Obtain 35 Million Woodcutting XP', 'Obtain 35 million experience in your Woodcutting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100049, '350 Collection log slots', 'Obtain 350 unique Collection Log slots.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101245, 'Obtain 50 Million Agility XP', 'Obtain 50 million experience in your Agility skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101246, 'Obtain 50 Million Attack XP', 'Obtain 50 million experience in your Attack skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101247, 'Obtain 50 Million Construction XP', 'Obtain 50 million experience in your Construction skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101248, 'Obtain 50 Million Cooking XP', 'Obtain 50 million experience in your Cooking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101249, 'Obtain 50 Million Crafting XP', 'Obtain 50 million experience in your Crafting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101250, 'Obtain 50 Million Defence XP', 'Obtain 50 million experience in your Defence skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101251, 'Obtain 50 Million Farming XP', 'Obtain 50 million experience in your Farming skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101252, 'Obtain 50 Million Firemaking XP', 'Obtain 50 million experience in your Firemaking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101253, 'Obtain 50 Million Fishing XP', 'Obtain 50 million experience in your Fishing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101254, 'Obtain 50 Million Fletching XP', 'Obtain 50 million experience in your Fletching skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101255, 'Obtain 50 Million Herblore XP', 'Obtain 50 million experience in your Herblore skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101256, 'Obtain 50 Million Hitpoints XP', 'Obtain 50 million experience in your Hitpoints skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101257, 'Obtain 50 Million Hunter XP', 'Obtain 50 million experience in your Hunter skill.', 'Elite', 200, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (101258, 'Obtain 50 Million Magic XP', 'Obtain 50 million experience in your Magic skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101259, 'Obtain 50 Million Mining XP', 'Obtain 50 million experience in your Mining skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101260, 'Obtain 50 Million Prayer XP', 'Obtain 50 million experience in your Prayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101261, 'Obtain 50 Million Ranged XP', 'Obtain 50 million experience in your Ranged skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101262, 'Obtain 50 Million Runecraft XP', 'Obtain 50 million experience in your Runecraft skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101263, 'Obtain 50 Million Slayer XP', 'Obtain 50 million experience in your Slayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101264, 'Obtain 50 Million Smithing XP', 'Obtain 50 million experience in your Smithing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101265, 'Obtain 50 Million Strength XP', 'Obtain 50 million experience in your Strength skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101266, 'Obtain 50 Million Thieving XP', 'Obtain 50 million experience in your Thieving skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101267, 'Obtain 50 Million Woodcutting XP', 'Obtain 50 million experience in your Woodcutting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100063, '500 Collection log slots', 'Obtain 500 unique Collection Log slots.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100088, 'Activate an Imbued Heart', 'Obtain and activate an Imbued heart.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101273, 'Obtain a Boss Pet', 'Obtain any Boss Pet.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101281, 'Obtain a Skilling Pet', 'Obtain any Skilling Pet.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100022, '100 Elite Clue Scrolls', 'Open 100 Reward caskets for completing Elite clue scrolls.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100023, '100 Master Clue Scrolls', 'Open 100 Reward caskets for completing Master clue scrolls.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100067, '75 Master Clue Scrolls', 'Open 75 Reward caskets for completing Master clue scrolls.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101419, 'Reach Total Level 2000', 'Reach a Total Level of 2000.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101420, 'Reach Total Level 2100', 'Reach a Total Level of 2100.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101421, 'Reach Total Level 2200', 'Reach a Total Level of 2200.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101385, 'Reach Combat Level 120', 'Reach Combat Level 120.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101386, 'Reach Combat Level 126', 'Reach Combat Level 126.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101380, 'Reach Base Level 80', 'Reach level 80 in every skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100082, 'Achieve Your First Level 90', 'Reach level 90 in any skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101381, 'Reach Base Level 90', 'Reach level 90 in every skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100083, 'Achieve Your First Level 95', 'Reach level 95 in any skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101391, 'Reach Level 99 Agility', 'Reach level 99 in your Agility skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101392, 'Reach Level 99 Attack', 'Reach level 99 in your Attack skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101393, 'Reach Level 99 Construction', 'Reach level 99 in your Construction skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101394, 'Reach Level 99 Cooking', 'Reach level 99 in your Cooking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101395, 'Reach Level 99 Crafting', 'Reach level 99 in your Crafting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101396, 'Reach Level 99 Defence', 'Reach level 99 in your Defence skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101397, 'Reach Level 99 Farming', 'Reach level 99 in your Farming skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101398, 'Reach Level 99 Firemaking', 'Reach level 99 in your Firemaking skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101399, 'Reach Level 99 Fishing', 'Reach level 99 in your Fishing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101400, 'Reach Level 99 Fletching', 'Reach level 99 in your Fletching skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101401, 'Reach Level 99 Herblore', 'Reach level 99 in your Herblore skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101402, 'Reach Level 99 Hitpoints', 'Reach level 99 in your Hitpoints skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101403, 'Reach Level 99 Hunter', 'Reach level 99 in your Hunter skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101404, 'Reach Level 99 Magic', 'Reach level 99 in your Magic skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101405, 'Reach Level 99 Mining', 'Reach level 99 in your Mining skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101406, 'Reach Level 99 Prayer', 'Reach level 99 in your Prayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101407, 'Reach Level 99 Ranged', 'Reach level 99 in your Ranged skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101408, 'Reach Level 99 Runecraft', 'Reach level 99 in your Runecraft skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101409, 'Reach Level 99 Slayer', 'Reach level 99 in your Slayer skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101410, 'Reach Level 99 Smithing', 'Reach level 99 in your Smithing skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101411, 'Reach Level 99 Strength', 'Reach level 99 in your Strength skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101412, 'Reach Level 99 Thieving', 'Reach level 99 in your Thieving skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101413, 'Reach Level 99 Woodcutting', 'Reach level 99 in your Woodcutting skill.', 'Elite', 200, 'General', NULL, 'demonic', false),
  (101479, 'Smith a Dragonfire Shield', 'Use an Anvil to smith a Dragonfire Shield.', 'Elite', 200, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100249, 'Combat Achievements Hard Tier', '', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100250, 'Combat Achievements Medium Tier', '', 'Elite', 200, 'General', NULL, 'demonic', false),
  (100115, 'Build a Demonic Throne', 'Build a Demonic Throne in a Throne Room in your Player Owned House.', 'Master', 400, 'General', NULL, 'demonic', false),
  (100825, 'Equip a Scythe of Vitur', 'Equip a Scythe of Vitur.', 'Master', 400, 'General', NULL, 'demonic', false),
  (100843, 'Equip a Twisted Bow', 'Equip a Twisted bow.', 'Master', 400, 'General', NULL, 'demonic', false),
  (100921, 'Equip full Virtus', 'Equip full Virtus outfit, obtained from Desert Treasure II bosses.', 'Master', 400, 'General', NULL, 'demonic', false),
  (100956, 'Equip the Tumeken''s Shadow', 'Equip the Tumeken''s Shadow.', 'Master', 400, 'General', NULL, 'demonic', false),
  (101205, 'Obtain 200 Million XP in any non-combat skill', 'Obtain 200 million experience in any non-combat skill.', 'Master', 400, 'General', NULL, 'demonic', false),
  (101204, 'Obtain 200 Million XP in a combat skill', 'Obtain 200 million experience in either Attack, Strength, Defence, Magic, Ranged or Hitpoints.', 'Master', 400, 'General', NULL, 'demonic', false),
  (101268, 'Obtain 50 Million XP in 3 non-combat skills', 'Obtain 50 million experience in 3 different skills excluding Attack, Strength, Defence, Magic, Ranged & Hitpoints.', 'Master', 400, 'General', NULL, 'demonic', false),
  (100070, '750 Collection log slots', 'Obtain 750 unique Collection Log slots.', 'Master', 400, 'General', NULL, 'demonic', false),
  (101382, 'Reach Base Level 95', 'Reach level 95 in every skill.', 'Master', 400, 'General', NULL, 'demonic', false),
  (101422, 'Reach Total Level 2277', 'Reach the highest possible Total Level of 2277.', 'Master', 400, 'General', NULL, 'demonic', false),
  (100248, 'Combat Achievements Elite Tier', '', 'Master', 400, 'General', NULL, 'demonic', false),
  (100188, 'Catch a Karambwanji', 'Catch a Karambwanji on Karamja.', 'Easy', 10, 'Karamja', NULL, 'demonic', false),
  (100991, 'Fill a Crate With Bananas', 'Fill a crate with Bananas for Luthas at Musa Point.', 'Easy', 10, 'Karamja', NULL, 'demonic', false),
  (101125, 'Defeat a Snake in Karamja', 'Defeat a Snake in Karamja.', 'Easy', 10, 'Karamja', NULL, 'demonic', false),
  (101335, 'Pick a Pineapple on Karamja', 'Pick a Pineapple on Karamja.', 'Easy', 10, 'Karamja', NULL, 'demonic', false),
  (101431, 'Receive an Agility Arena Ticket', 'Receive an Agility Arena Ticket from the Brimhaven Agility Arena.', 'Easy', 10, 'Karamja', NULL, 'demonic', false),
  (100140, 'Buy a Snapdragon From Pirate Jackie the Fruit', 'Buy a Snapdragon From Pirate Jackie the Fruit in Brimhaven.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100172, 'Catch 50 Karambwan', 'Catch 50 Karambwan on Karamja.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100196, 'Catch a Salmon on Karamja', 'Catch a Salmon on Karamja.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100228, 'Chop a dense jungle', 'Fully clear a dense jungle in the Tai Bwo Wannai Cleanup.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100315, 'Complete the Easy Karamja Diary', 'Complete all of the Easy tasks in the Karamja Achievement Diary.', 'Medium', 40, 'Karamja', 'See Karamja Diary#Easy', 'demonic', false),
  (100357, 'Complete the Medium Karamja Diary', 'Complete all of the Medium tasks in the Karamja Achievement Diary.', 'Medium', 40, 'Karamja', 'See Karamja Diary#Medium', 'demonic', false),
  (100425, 'Craft 50 Nature Runes', 'Craft 50 Nature Runes from Essence at the Nature Altar.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100488, 'Defeat a Black Demon on Karamja', 'Defeat a Black Demon on Karamja.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100532, 'Defeat a TzHaar', 'Defeat any TzHaar in Mor Ul Rek.', 'Medium', 40, 'Karamja', NULL, 'demonic', true),
  (100672, 'Enter the Brimhaven Dungeon', 'Enter the Brimhaven Dungeon.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100681, 'Enter the Tai Bwo Wannai Hardwood Grove', 'Enter the Hardwood Grove in Tai Bwo Wannai.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100759, 'Equip a Full Tai Bwo Wannai Villager Set', 'Equip a full set of Tai Bwo Wannai villager clothing.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100836, 'Equip a Toktz-Ket-Xil', 'Equip a Toktz-Ket-Xil.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100837, 'Equip a Toktz-Xil-Ak', 'Equip a Toktz-Xil-Ak.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100838, 'Equip a Toktz-Xil-Ek', 'Equip a Toktz-Xil-Ek.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100880, 'Equip an Obsidian Cape', 'Equip an Obsidian cape.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100892, 'Equip any spear (kp)', 'Equip any spear poisoned by a karambwan.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (101467, 'Sleep in Paramaya Inn', 'Pay the barkeep to sleep in Paramaya Inn, in Shilo Village.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (101521, 'Take a Shortcut Across the Shilo Village River', 'Use the Stepping Stones Agility Shortcut in Shilo Village.', 'Medium', 40, 'Karamja', NULL, 'demonic', false),
  (100094, 'Admire some beautiful scenery', 'Admire some beautiful scenery in Auburnvale or the Auburn Valley.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100112, 'Bow near a quetzal', 'Bow near a quetzal.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100206, 'Charter a Ship From Sunset Coast to Civitas', 'Take a Charter Ship from Sunset Coast to Civitas illa Fortis.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100230, 'Chop a tree in the Tlati Rainforest', 'Chop a tree in the Tlati Rainforest.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100379, 'Complete the Vale totems miniquest', 'Complete the Vale totems miniquest.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100471, 'Cry near a child', 'Cry near a child.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100477, 'Dance near a bard', 'Dance near a bard.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100655, 'Drink a cup of tea in auburn valley', 'Drink a cup of tea in auburn valley.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100659, 'Drink from a bird bath', 'Drink from a bird bath.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100661, 'Drink some moon-lite', 'Drink some moon-lite.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100970, 'Exit civitas via the secret passage', 'Exit civitas via the secret passage.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false),
  (100989, 'Fill a bucket with sand at the Sunset coast', 'Fill a bucket with sand at the Sunset coast.', 'Easy', 10, 'Varlamore', NULL, 'demonic', false);
