-- Pact tasks for Demonic Pacts League
-- Generated on 2026-04-09
-- Total tasks: 75

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (10001, 'Complete the Leagues Tutorial', 'Complete the Leagues Tutorial and begin your adventure.', 'Easy', 10, 'General', null, 'demonic', true),
  (10002, 'Open the Leagues Menu', 'Open the Leagues Menu found within the Journal Panel.', 'Easy', 10, 'General', null, 'demonic', true),
  (10003, 'Defeat a Hill Giant', 'Defeat a Hill Giant.', 'Easy', 10, 'General', null, 'demonic', true),
  (10004, 'Reach Combat Level 50', 'Reach Combat Level 50.', 'Medium', 40, 'General', null, 'demonic', true),
  (10005, 'Use the Protect from Melee Prayer', 'Use the Protect from Melee Prayer.', 'Medium', 40, 'General', null, 'demonic', true),
  (10006, 'Kill 1 unique Echo Boss', 'Kill 1 unique Echo Boss.', 'Hard', 80, 'General', null, 'demonic', true),
  (10007, 'Kill 2 unique Echo Bosses', 'Kill 2 unique Echo Bosses.', 'Hard', 80, 'General', null, 'demonic', true),
  (10008, 'Kill 3 unique Echo Bosses', 'Kill 3 unique Echo Bosses.', 'Hard', 80, 'General', null, 'demonic', true),
  (10009, 'Kill 4 unique Echo Bosses', 'Kill 4 unique Echo Bosses.', 'Elite', 200, 'General', null, 'demonic', true),
  (10010, 'Equip Avernic Treads', 'Equip Avernic treads.', 'Elite', 200, 'Varlamore', null, 'demonic', true),
  (10011, 'Complete Wave 12 of Fortis Colosseum', 'Complete Wave 12 of Fortis Colosseum.', 'Elite', 200, 'Varlamore', null, 'demonic', true),
  (10012, 'Defeat Awakened Vardorvis', 'Defeat Awakened Vardorvis.', 'Elite', 200, 'Varlamore', null, 'demonic', true),
  (10013, '1 Hueycoatl Kill', 'Kill the Hueycoatl in Varlamore.', 'Medium', 40, 'Varlamore', null, 'demonic', true),
  (10014, 'Defeat a Steel Dragon on Karamja', 'Defeat a Steel Dragon on Karamja.', 'Medium', 40, 'Karamja', null, 'demonic', true),
  (10015, 'Defeat a TzHaar', 'Defeat any TzHaar in Mor Ul Rek.', 'Medium', 40, 'Karamja', null, 'demonic', true),
  (10016, 'Complete Tzhaar-Ket-Rak''s third challenge', 'Complete Tzhaar-Ket-Rak''s third challenge.', 'Hard', 80, 'Karamja', null, 'demonic', true),
  (10017, 'Equip a Fire Cape', 'Equip a Fire Cape.', 'Elite', 200, 'Karamja', null, 'demonic', true),
  (10018, 'Complete Tzhaar-Ket-Rak''s Special challenge', 'Complete Tzhaar-Ket-Rak''s league-only challenge.', 'Master', 400, 'Karamja', null, 'demonic', true),
  (10019, 'Equip an Infernal Cape', 'Equip an Infernal Cape.', 'Master', 400, 'Karamja', null, 'demonic', true),
  (10020, 'Defeat a Troll in Asgarnia', 'Defeat a Troll in Asgarnia.', 'Easy', 10, 'Asgarnia', null, 'demonic', true),
  (10021, 'Defeat the Royal Titans solo', 'Defeat the Royal Titans without any other player joining.', 'Hard', 80, 'Asgarnia', null, 'demonic', true),
  (10022, 'Equip a Dragon Defender', 'Equip a Dragon Defender.', 'Hard', 80, 'Asgarnia', null, 'demonic', true),
  (10023, 'Defeat Awakened Whisperer', 'Defeat Awakened Whisperer.', 'Elite', 200, 'Asgarnia', null, 'demonic', true),
  (10024, 'Equip a Godsword', 'Equip any Godsword.', 'Elite', 200, 'Asgarnia', null, 'demonic', true),
  (10025, 'Equip the Bellator Ring', 'Obtain and Equip the Bellator Ring.', 'Elite', 200, 'Asgarnia', null, 'demonic', true),
  (10026, 'Defeat Nex Solo', 'Defeat Nex in a private instance without help from any other player.', 'Master', 400, 'Asgarnia', null, 'demonic', true),
  (10027, 'Set a mummy ablaze', 'Set a Mummy on Fire with fire damage.', 'Easy', 10, 'Desert', null, 'demonic', true),
  (10028, 'Cast Ice Barrage', 'Cast the Ice Barrage spell.', 'Elite', 200, 'Desert', null, 'demonic', true),
  (10029, 'Defeat Awakened Leviathan', 'Defeat Awakened Leviathan.', 'Elite', 200, 'Desert', null, 'demonic', true),
  (10030, 'Equip a Dragon Chainbody in the Kharidian Desert', 'Equip a Dragon Chainbody in the Kharidian Desert.', 'Elite', 200, 'Desert', null, 'demonic', true),
  (10031, 'Equip a Piece of Masori Armour', 'Equip either a Masori Mask, a Masori Body or some Masori chaps.', 'Elite', 200, 'Desert', null, 'demonic', true),
  (10032, 'Equip the Venator Ring', 'Obtain and Equip the Venator Ring.', 'Elite', 200, 'Desert', null, 'demonic', true),
  (10033, 'Equip Osmumten''s Fang (or)', 'Obtain and Equip Osmumten''s Fang (or).', 'Master', 400, 'Desert', null, 'demonic', true),
  (10034, 'Defeat a Cockatrice in the Fremennik Province', 'Defeat a Cockatrice in the Fremennik Province.', 'Easy', 10, 'Fremennik', null, 'demonic', true),
  (10035, 'Kill 8 penguins within 5 seconds', 'Kill 8 penguins within 5 seconds.', 'Medium', 40, 'Fremennik', null, 'demonic', true),
  (10036, 'Defeat Phantom Muspah', 'Defeat Phantom Muspah.', 'Hard', 80, 'Fremennik', null, 'demonic', true),
  (10037, 'Defeat a Basilisk Knight', 'Defeat a Basilisk Knight in the Jormungand''s Prison.', 'Hard', 80, 'Fremennik', null, 'demonic', true),
  (10038, 'Defeat Vorkath 5 Times Without Special Damage', 'Defeat Vorkath on Ungael 5 times in a row without taking any damage from his special attacks and without leaving his area. Failing this task requires you to leave the instance to try again.', 'Elite', 200, 'Fremennik', null, 'demonic', true),
  (10039, 'Defeat Awakened Duke Sucellus', 'Defeat Awakened Duke Sucellus.', 'Elite', 200, 'Fremennik', null, 'demonic', true),
  (10040, 'Equip the Magus Ring', 'Obtain and Equip the Magus Ring.', 'Elite', 200, 'Fremennik', null, 'demonic', true),
  (10041, 'Defeat a Demonic Gorilla', 'Defeat a Demonic Gorilla in the Crash Site Cavern.', 'Hard', 80, 'Kandarin', null, 'demonic', true),
  (10042, 'Defeat a Mithril Dragon', 'Defeat a Mithril Dragon in the Ancient Cavern.', 'Hard', 80, 'Kandarin', null, 'demonic', true),
  (10043, 'Defeat the Kraken Boss 50 Times', 'Defeat the Kraken boss in Kraken Cove 50 times.', 'Hard', 80, 'Kandarin', null, 'demonic', true),
  (10044, 'Equip a Trident of the Seas', 'Equip a Trident of the Seas.', 'Hard', 80, 'Kandarin', null, 'demonic', true),
  (10045, 'Equip an Abyssal Tentacle', 'Equip an Abyssal Tentacle.', 'Elite', 200, 'Kandarin', null, 'demonic', true),
  (10046, 'Equip an Occult Necklace', 'Equip an Occult Necklace.', 'Elite', 200, 'Kandarin', null, 'demonic', true),
  (10047, 'Equip Some Zenyte Jewelry', 'Equip any piece of Zenyte Jewelry.', 'Elite', 200, 'Kandarin', null, 'demonic', true),
  (10048, 'Open 1 Grubby Chest', 'Open the grubby chest in the Forthos Dungeon.', 'Easy', 10, 'Kourend', null, 'demonic', true),
  (10049, '150 Lizardmen Shaman Kills', 'Help the Shayzien House by killing 150 Lizardmen shamans.', 'Medium', 40, 'Kourend', null, 'demonic', true),
  (10050, '25 Chambers of Xeric', 'Complete the Chambers of Xeric Normal or Challenge Mode 25 times.', 'Hard', 80, 'Kourend', null, 'demonic', true),
  (10051, '1 Skotizo Kill', 'Kill Skotizo beneath the Catacombs of Kourend.', 'Hard', 80, 'Kourend', null, 'demonic', true),
  (10052, 'Equip a piece of Radiant Oathplate', 'Equip a piece of Radiant oathplate armour.', 'Elite', 200, 'Kourend', null, 'demonic', true),
  (10053, 'Equip any Ancestral piece', 'Equip either an Ancestral Hat, an Ancestral robe top or an Ancestral robe bottom.', 'Elite', 200, 'Kourend', null, 'demonic', true),
  (10054, 'Equip a Dragon Hunter Lance', 'Obtain and equip a Dragon hunter lance.', 'Elite', 200, 'Kourend', null, 'demonic', true),
  (10055, 'Defeat a Werewolf in Morytania', 'Defeat a Werewolf in Morytania.', 'Easy', 10, 'Morytania', null, 'demonic', true),
  (10056, 'Assemble a Slayer Helm', 'Assemble a Slayer Helm.', 'Hard', 80, 'Morytania', null, 'demonic', true),
  (10057, 'Create an Amulet of Blood Fury', 'Create an Amulet of Blood Fury.', 'Hard', 80, 'Morytania', null, 'demonic', true),
  (10058, 'Equip any Full Barrows Armour Set', 'Equip a full set of any Barrows armour + weapon.', 'Hard', 80, 'Morytania', null, 'demonic', true),
  (10059, '1 Araxxor Kill', 'Kill the Araxxor in Morytania Spider Cave.', 'Hard', 80, 'Morytania', null, 'demonic', true),
  (10060, 'Complete the Theatre of Blood 25 Times', 'Complete the Theatre of Blood on Normal or Hard Mode 25 times.', 'Elite', 200, 'Morytania', null, 'demonic', true),
  (10061, 'Defeat Phosani''s Nightmare', 'Defeat Phosani''s Nightmare in the Sisterhood Sanctuary.', 'Elite', 200, 'Morytania', null, 'demonic', true),
  (10062, 'Kill a Black Dragon in Tirannwn', 'Kill a Black Dragon in Tirannwn.', 'Medium', 40, 'Tirannwn', null, 'demonic', true),
  (10063, 'Complete the Corrupted Gauntlet', 'Complete the Corrupted Gauntlet in Prifddinas.', 'Hard', 80, 'Tirannwn', null, 'demonic', true),
  (10064, 'Defeat Zalcano', 'Defeat Zalcano in Prifddinas.', 'Hard', 80, 'Tirannwn', null, 'demonic', true),
  (10065, 'Equip a Dark Bow in Tirannwn', 'Equip a Dark Bow in Tirannwn.', 'Hard', 80, 'Tirannwn', null, 'demonic', true),
  (10066, 'Craft a Toxic Blowpipe', 'Craft a Toxic Blowpipe.', 'Elite', 200, 'Tirannwn', null, 'demonic', true),
  (10067, 'Use a prayer altar to restore 90 prayer in Prifddinas', 'Use a prayer altar to restore 90 prayer points in Prifddinas.', 'Elite', 200, 'Tirannwn', null, 'demonic', true),
  (10068, 'Equip a Corrupted Weapon', 'Equip a Corrupted Blade of Saeldor or Bow of Faerdhinen.', 'Master', 400, 'Tirannwn', null, 'demonic', true),
  (10069, 'Defeat a Chaos Dwarf in the Wilderness', 'Defeat a Chaos Dwarf in the Wilderness.', 'Easy', 10, 'Wilderness', null, 'demonic', true),
  (10070, 'Defeat the Corporeal Beast', 'Defeat the Corporeal Beast in the Wilderness.', 'Hard', 80, 'Wilderness', null, 'demonic', true),
  (10071, 'Equip a Dragon 2-Handed Sword in the Wilderness', 'Equip a Dragon 2-Handed Sword in the Wilderness.', 'Hard', 80, 'Wilderness', null, 'demonic', true),
  (10072, 'Equip a Malediction Ward', 'Equip a Malediction Ward.', 'Hard', 80, 'Wilderness', null, 'demonic', true),
  (10073, 'Equip a Piece of the Dagon''Hai Set', 'Equip any piece of the Dagon''hai robe set.', 'Elite', 200, 'Wilderness', null, 'demonic', true),
  (10074, 'Imbue a God Cape', 'Imbue either a Saradomin Cape, a Guthix Cape or a Zamorak Cape.', 'Elite', 200, 'Wilderness', null, 'demonic', true),
  (10075, 'Equip the Voidwaker', 'Obtain and Equip the Voidwaker.', 'Elite', 200, 'Wilderness', null, 'demonic', true)
ON CONFLICT (id) DO NOTHING;
