-- Demonic Pacts League tasks (685 total) from OSRS Wiki
-- RLS temporarily disabled for migration writes

-- Temporarily disable RLS so migration role can write
ALTER TABLE official_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE route_steps DISABLE ROW LEVEL SECURITY;

-- Step 1: Remove any existing demonic tasks with offset IDs (for re-runs)
DELETE FROM official_tasks WHERE id BETWEEN 100000 AND 199999 AND league = 'demonic';

-- Step 2: Insert all Demonic Pacts League tasks

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100529, 'Defeat a Troll in Asgarnia', 'Defeat a Troll in Asgarnia.', 'Easy', 10, 'Asgarnia', NULL, 'demonic', true),
  (101460, 'Set a Mummy ablaze', 'Set a Mummy on Fire with fire damage.', 'Easy', 10, 'Desert', NULL, 'demonic', true),
  (100496, 'Defeat a Cockatrice in the Fremennik Province', 'Defeat a Cockatrice in the Fremennik Province.', 'Easy', 10, 'Fremennik', NULL, 'demonic', true),
  (100506, 'Defeat a Hill Giant', 'Defeat a Hill Giant', 'Easy', 10, 'General', NULL, 'demonic', true),
  (100350, 'Complete the Leagues Tutorial', 'Complete the Leagues Tutorial and begin your adventure.', 'Easy', 10, 'General', NULL, 'demonic', true),
  (101318, 'Open the Leagues Menu', 'Open the Leagues Menu found within the Journal Panel.', 'Easy', 10, 'General', NULL, 'demonic', true),
  (101297, 'Open 1 Grubby Chest', 'Open the grubby chest in the Forthos Dungeon.', 'Easy', 10, 'Kourend', NULL, 'demonic', true),
  (100535, 'Defeat a Werewolf in Morytania', 'Defeat a Werewolf in Morytania.', 'Easy', 10, 'Morytania', NULL, 'demonic', true),
  (100494, 'Defeat a Chaos Dwarf in the Wilderness', 'Defeat a Chaos Dwarf in the Wilderness.', 'Easy', 10, 'Wilderness', NULL, 'demonic', true),
  (100546, 'Defeat Awakened Whisperer', 'Defeat Awakened Whisperer.', 'Elite', 200, 'Asgarnia', NULL, 'demonic', true),
  (100765, 'Equip a Godsword', 'Equip any Godsword.', 'Elite', 200, 'Asgarnia', NULL, 'demonic', true),
  (100942, 'Equip the Bellator Ring', 'Obtain and Equip the Bellator Ring.', 'Elite', 200, 'Asgarnia', NULL, 'demonic', true),
  (100149, 'Cast Ice Barrage', 'Cast the Ice Barrage spell.', 'Elite', 200, 'Desert', NULL, 'demonic', true),
  (100544, 'Defeat Awakened Leviathan', 'Defeat Awakened Leviathan.', 'Elite', 200, 'Desert', NULL, 'demonic', true),
  (100709, 'Equip a Dragon Chainbody in the Kharidian Desert', 'Equip a Dragon Chainbody in the Kharidian Desert.', 'Elite', 200, 'Desert', NULL, 'demonic', true),
  (100800, 'Equip a Piece of Masori Armour', 'Equip either a Masori Mask, a Masori Body or some Masori chaps.', 'Elite', 200, 'Desert', NULL, 'demonic', true),
  (100960, 'Equip the Venator Ring', 'Obtain and Equip the Venator Ring.', 'Elite', 200, 'Desert', NULL, 'demonic', true),
  (100635, 'Defeat Vorkath 5 Times Without Special Damage', 'Defeat Vorkath on Ungael 5 times in a row without taking any damage from his special attacks and without leaving his area. Failing this task requires you to leave the instance to try again.', 'Elite', 200, 'Fremennik', NULL, 'demonic', true),
  (100543, 'Defeat Awakened Duke Sucellus', 'Defeat Awakened Duke Sucellus.', 'Elite', 200, 'Fremennik', NULL, 'demonic', true),
  (100951, 'Equip the Magus Ring', 'Obtain and Equip the Magus Ring.', 'Elite', 200, 'Fremennik', NULL, 'demonic', true),
  (100858, 'Equip an Abyssal Tentacle', 'Equip an Abyssal Tentacle.', 'Elite', 200, 'Kandarin', NULL, 'demonic', true),
  (100881, 'Equip an Occult Necklace', 'Equip an Occult Necklace.', 'Elite', 200, 'Kandarin', NULL, 'demonic', true),
  (100936, 'Equip Some Zenyte Jewelry', 'Equip any piece of Zenyte Jewelry.', 'Elite', 200, 'Kandarin', NULL, 'demonic', true),
  (100724, 'Equip a Fire Cape', 'Equip a Fire Cape.', 'Elite', 200, 'Karamja', NULL, 'demonic', true),
  (100802, 'Equip a piece of Radiant Oathplate', 'Equip a piece of Radiant oathplate armour.', 'Elite', 200, 'Kourend', NULL, 'demonic', true),
  (100887, 'Equip any Ancestral piece', 'Equip either an Ancestral Hat, an Ancestral robe top or an Ancestral robe bottom.', 'Elite', 200, 'Kourend', NULL, 'demonic', true),
  (100714, 'Equip a Dragon Hunter Lance', 'Obtain and equip a Dragon hunter lance.', 'Elite', 200, 'Kourend', NULL, 'demonic', true),
  (100377, 'Complete the Theatre of Blood 25 Times', 'Complete the Theatre of Blood on Normal or Hard Mode 25 times.', 'Elite', 200, 'Morytania', NULL, 'demonic', true),
  (100580, 'Defeat Phosani''s Nightmare', 'Defeat Phosani''s Nightmare in the Sisterhood Sanctuary.', 'Elite', 200, 'Morytania', NULL, 'demonic', true),
  (100435, 'Craft a Toxic Blowpipe', 'Craft a Toxic Blowpipe.', 'Elite', 200, 'Tirannwn', NULL, 'demonic', true),
  (101572, 'Use a prayer altar to restore 90 prayer in Prifddinas', 'Use a prayer altar to restore 90 prayer points in Prifddinas.', 'Elite', 200, 'Tirannwn', NULL, 'demonic', true),
  (100894, 'Equip Avernic Treads', 'Equip Avernic treads.', 'Elite', 200, 'Varlamore', NULL, 'demonic', true),
  (100395, 'Complete Wave 12 of Fortis Colosseum', 'Complete Wave 12 of Fortis Colosseum.', 'Elite', 200, 'Varlamore', NULL, 'demonic', true),
  (100545, 'Defeat Awakened Vardorvis', 'Defeat Awakened Vardorvis.', 'Elite', 200, 'Varlamore', NULL, 'demonic', true),
  (100806, 'Equip a Piece of the Dagon''Hai Set', 'Equip any piece of the Dagon''hai robe set.', 'Elite', 200, 'Wilderness', NULL, 'demonic', true),
  (101082, 'Imbue a God Cape', 'Imbue either a Saradomin Cape, a Guthix Cape or a Zamorak Cape.', 'Elite', 200, 'Wilderness', NULL, 'demonic', true),
  (100961, 'Equip the Voidwaker', 'Obtain and Equip the Voidwaker.', 'Elite', 200, 'Wilderness', NULL, 'demonic', true),
  (100618, 'Defeat the Royal Titans solo', 'Defeat the Royal Titans without any other player joining.', 'Hard', 80, 'Asgarnia', NULL, 'demonic', true),
  (100711, 'Equip a Dragon Defender', 'Equip a Dragon Defender.', 'Hard', 80, 'Asgarnia', NULL, 'demonic', true),
  (100576, 'Defeat Phantom Muspah', 'Defeat Phantom Muspah.', 'Hard', 80, 'Fremennik', NULL, 'demonic', true),
  (100486, 'Defeat a Basilisk Knight', 'Defeat a Basilisk Knight in the Jormungand''s Prison.', 'Hard', 80, 'Fremennik', NULL, 'demonic', true),
  (100499, 'Defeat a Demonic Gorilla', 'Defeat a Demonic Gorilla in the Crash Site Cavern.', 'Hard', 80, 'Kandarin', NULL, 'demonic', true),
  (100514, 'Defeat a Mithril Dragon', 'Defeat a Mithril Dragon in the Ancient Cavern.', 'Hard', 80, 'Kandarin', NULL, 'demonic', true),
  (100609, 'Defeat the Kraken Boss 50 Times', 'Defeat the Kraken boss in Kraken Cove 50 times.', 'Hard', 80, 'Kandarin', NULL, 'demonic', true),
  (100840, 'Equip a Trident of the Seas', 'Equip a Trident of the Seas.', 'Hard', 80, 'Kandarin', NULL, 'demonic', true),
  (100393, 'Complete Tzhaar-Ket-Rak''s third challenge', 'Complete Tzhaar-Ket-Rak''s third challenge.', 'Hard', 80, 'Karamja', NULL, 'demonic', true),
  (100034, '25 Chambers of Xeric', 'Complete the Chambers of Xeric Normal or Challenge Mode 25 times.', 'Hard', 80, 'Kourend', NULL, 'demonic', true),
  (100014, 'Defeat Skotizo 1 Time', 'Kill Skotizo beneath the Catacombs of Kourend.', 'Hard', 80, 'Kourend', NULL, 'demonic', true),
  (100098, 'Assemble a Slayer Helm', 'Assemble a Slayer Helm.', 'Hard', 80, 'Morytania', NULL, 'demonic', true),
  (100461, 'Create an Amulet of Blood Fury', 'Create an Amulet of Blood Fury.', 'Hard', 80, 'Morytania', NULL, 'demonic', true);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100888, 'Equip any Full Barrows Armour Set', 'Equip a full set of any Barrows armour + weapon.', 'Hard', 80, 'Morytania', NULL, 'demonic', true),
  (100004, 'Defeat Araxxor 1 Time', 'Kill the Araxxor in Morytania Spider cave.', 'Hard', 80, 'Morytania', NULL, 'demonic', true),
  (100306, 'Complete the Corrupted Gauntlet', 'Complete the Corrupted Gauntlet in Prifddinas.', 'Hard', 80, 'Tirannwn', NULL, 'demonic', true),
  (100641, 'Defeat Zalcano', 'Defeat Zalcano in Prifddinas.', 'Hard', 80, 'Tirannwn', NULL, 'demonic', true),
  (100705, 'Equip a Dark Bow in Tirannwn', 'Equip a Dark Bow in Tirannwn.', 'Hard', 80, 'Tirannwn', NULL, 'demonic', true),
  (100591, 'Defeat the Corporeal Beast', 'Defeat the Corporeal Beast in the Wilderness.', 'Hard', 80, 'Wilderness', NULL, 'demonic', true),
  (100707, 'Equip a Dragon 2-Handed Sword in the Wilderness', 'Equip a Dragon 2-Handed Sword in the Wilderness.', 'Hard', 80, 'Wilderness', NULL, 'demonic', true),
  (100778, 'Equip a Malediction Ward', 'Equip a Malediction Ward.', 'Hard', 80, 'Wilderness', NULL, 'demonic', true),
  (100575, 'Defeat Nex Solo', 'Defeat Nex in a private instance without help from any other player.', 'Master', 400, 'Asgarnia', NULL, 'demonic', true),
  (100925, 'Equip the Osmumten''s Fang (or)', 'Obtain and Equip Osmumten''s Fang (or).', 'Master', 400, 'Desert', NULL, 'demonic', true),
  (100392, 'Complete Tzhaar-Ket-Rak''s Special challenge', 'Complete Tzhaar-Ket-Rak''s league-only challenge.', 'Master', 400, 'Karamja', NULL, 'demonic', true),
  (100877, 'Equip an Infernal Cape', 'Equip an Infernal Cape.', 'Master', 400, 'Karamja', NULL, 'demonic', true),
  (100699, 'Equip a Corrupted Weapon', 'Equip a Corrupted Blade of Saeldor or Bow of Faerdhinen', 'Master', 400, 'Tirannwn', 'or and', 'demonic', true),
  (101100, 'Defeat 8 penguins within 5 seconds', 'Kill 8 penguins within 5 seconds.', 'Medium', 40, 'Fremennik', NULL, 'demonic', true),
  (101590, 'Use the Protect from Melee Prayer', 'Use the Protect from Melee Prayer.', 'Medium', 40, 'General', NULL, 'demonic', true),
  (100526, 'Defeat a Steel Dragon on Karamja', 'Defeat a Steel Dragon on Karamja.', 'Medium', 40, 'Karamja', NULL, 'demonic', true),
  (100029, 'Defeat 150 Lizardmen Shaman', 'Help the Shayzien House by killing 150 Lizardmen shamans.', 'Medium', 40, 'Kourend', NULL, 'demonic', true),
  (101103, 'Defeat a Black Dragon in Tirannwn', 'Kill a Black Dragon in Tirannwn.', 'Medium', 40, 'Tirannwn', NULL, 'demonic', true),
  (100073, 'Achieve Your First Level 10', 'Reach level 10 in any skill (not including Agility and Hitpoints).', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100077, 'Achieve Your First Level 5', 'Reach level 5 in any skill (not including Agility, Hitpoints and Runecraft).', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100084, 'Achieve Your First Level Up', 'Level up any of your skills for the first time.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100085, 'Activate a prayer near an altar', 'Activate a prayer near an altar', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100100, 'Attack a dummy', 'Attack a dummy.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100130, 'Burn Some Food', 'Burn any kind of food while trying to cook it.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100132, 'Burn Some Normal Logs', 'Burn some Normal Logs.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100133, 'Burn Some Oak Logs', 'Burn some Oak Logs.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100134, 'Bury 6 bones', 'Bury 6 bones of any kind', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100148, 'Cast Home Teleport', 'Cast the Home Teleport spell.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100178, 'Catch a Baby Impling', 'Catch a Baby Impling.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100186, 'Catch a Herring', 'Catch a Raw Herring whilst Fishing.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100197, 'Catch a Shrimp', 'Catch Raw Shrimp while Fishing.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100202, 'Catch an Anchovy', 'Catch a Raw Anchovy whilst Fishing.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100232, 'Chop Some Logs', 'Chop any kind of logs.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100234, 'Chop Some Logs With a Steel Axe', 'Chop any kind of logs using a Steel Axe.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100238, 'Clean 15 Grimy Tarromin', 'Clean 15 Grimy Tarromin.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100239, 'Clean 25 Grimy Guam Leafs', 'Clean 25 Grimy Guam Leafs.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100244, 'Clean a Grimy Guam', 'Clean a Grimy Guam.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100411, 'Cook Shrimp', 'Cook Raw Shrimp.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100412, 'Cook something with an apron', 'Cook something with an apron equipped', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100443, 'Craft Leather chaps', 'Craft Leather chaps', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100462, 'Create an Antipoison', 'Create an Antipoison.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100474, 'Cut a Ruby', 'Cut a Ruby', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100495, 'Defeat a Chicken', 'Defeat a Chicken', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100658, 'Drink a Strength Potion', 'Drink a Strength Potion.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100664, 'Dye a cape Purple', 'Dye a cape Purple', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100666, 'Eat a Rabbit', 'Eat a cooked rabbit.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100667, 'Eat an Onion', 'Eat an Onion, raw.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100687, 'Enter your Player Owned House', 'Enter your Player Owned House.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100847, 'Equip a Tyras helm', 'Equip a Tyras helm', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100869, 'Equip an Elemental Staff', 'Equip a basic elemental staff.', 'Easy', 10, 'General', NULL, 'demonic', false);

INSERT INTO official_tasks (id, name, description, tier, points, region, skill, league, is_pact_task) VALUES
  (100879, 'Equip an Iron dagger', 'Equip an Iron dagger.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100971, 'Feed a dog some bones', 'Feed a dog some bones.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101016, 'Fletch an Oak Shortbow', 'Fletch an Oak Shortbow.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101017, 'Fletch Some Arrow Shafts', 'Fletch some Arrow Shafts.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101053, 'Get a haircut', 'Go and get a haircut.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101107, 'Defeat a Frog', 'Defeat a Frog.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101119, 'Defeat a Rat', 'Defeat a Rat.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101122, 'Defeat a scorpion', 'Defeat a scorpion', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101134, 'Defeat an Imp with an earth spell', 'Defeat an Imp with an earth spell.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101148, 'Light a Torch', 'Light a Torch.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101172, 'Make an Attack Potion', 'Make an Attack Potion.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101185, 'Mine 5 Tin Ore', 'Mine 5 Tin Ore.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101192, 'Mine some Clay', 'Mine some Clay', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101195, 'Mine some Ore With a Steel Pickaxe', 'Mine any ore using a Steel Pickaxe.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101272, 'Obtain a Bird Nest', 'Obtain a Bird Nest whilst cutting down trees.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101274, 'Obtain a Casket from Fishing', 'Obtain a Casket from Fishing.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101324, 'Perform a Special Attack', 'Perform any special attack.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101332, 'Pick 6 flax', 'Pick 6 flax', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101333, 'Pick 6 wheat, 6 cabbages and 6 potatoes', 'Pick 6 wheat, 6 cabbage and 6 potatoes', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101345, 'Pickpocket a Citizen', 'Pickpocket a Man or a Woman.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101359, 'Plant Seeds in an Allotment Patch', 'Plant some seeds in an Allotment patch.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101361, 'Protect Your Crops', 'Pay a farmer to protect any of your crops.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101363, 'Purchase a Player Owned House', 'Purchase a Player Owned House.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101369, 'Rake a Flower Patch', 'Rake a Flower Patch', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101387, 'Reach Combat Level 25', 'Reach Combat Level 25.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101459, 'Sell some silk to a silk trader', 'Sell some silk to a silk trader', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101463, 'Shoot 6 iron arrows', 'Shoot 6 iron arrows', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101468, 'Smelt a Bronze Bar', 'Use a Furnace to smelt a Bronze Bar.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101473, 'Smelt an Iron Bar', 'Use a Furnace to smelt an Iron Bar.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101485, 'Snare 15 Tropical Wagtails', 'Snare 15 Tropical Wagtails', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101486, 'Snare 5 Crimson Swifts', 'Snare 5 Crimson Swifts', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101487, 'Snare a Bird', 'Catch any bird with a Bird Snare.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101489, 'Spin a Ball of Wool', 'Use a Spinning Wheel to spin a Ball of Wool.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101507, 'Steal some bread', 'Steal some bread from a Bakery Stall', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101516, 'Successfully Cut a Red Topaz', 'Successfully Cut a Red Topaz.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101523, 'Talk to any Port master', 'Talk to any Port master', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101555, 'Turn any Logs Into a Plank', 'Use a Sawmill to turn Logs into a Plank.', 'Easy', 10, 'General', NULL, 'demonic', false),
  (101565, 'Turn off your run', 'Turn off your run', 'Easy', 10, 'General', NULL, 'demonic', false),
  (100006, '1 Easy Clue Scroll', 'Open a Reward casket for completing an Easy clue scroll.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100007, '1 Elite Clue Scroll', 'Open a Reward casket for completing an Elite clue scroll.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100008, '1 Hard Clue Scroll', 'Open a Reward casket for completing a Hard clue scroll.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100011, '1 Medium Clue Scroll', 'Open a Reward casket for completing a Medium clue scroll.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100025, '15 Collection log slots', 'Obtain 15 unique Collection Log slots.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100035, '25 Easy Clue Scrolls', 'Open 25 Reward caskets for completing Easy clue scrolls.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100036, '25 Elite Clue Scrolls', 'Open 25 Reward caskets for completing Elite clue scrolls.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100037, '25 Hard Clue Scrolls', 'Open 25 Reward caskets for completing Hard clue scrolls.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100039, '25 Medium Clue Scrolls', 'Open 25 Reward caskets for completing Medium clue scrolls.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100040, 'Defeat 25 Superior slayer creatures', 'Defeat 25 Superior slayer monsters.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100044, '30 Collection log slots', 'Obtain 30 unique Collection Log slots.', 'Medium', 40, 'General', NULL, 'demonic', false),
  (100050, '5 Collection log slots', 'Obtain 5 unique Collection Log slots.', 'Medium', 40, 'General', NULL, 'demonic', false);
